# Generated by Django 3.2.16 on 2026-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=150)),
                ('player2', models.CharField(max_length=150)),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('court', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('winner', models.CharField(blank=True, max_length=150, null=True)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=150)),
                ('amount', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=50)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=50)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=10)),
                ('joinDate', models.DateField()),
                ('matchesPlayed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('court', models.CharField(max_length=50)),
                ('coach', models.CharField(max_length=150)),
                ('players', models.IntegerField(default=0)),
                ('maxPlayers', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('fee', models.IntegerField(default=0)),
            ],
        ),
    ]
