# Generated by Django 4.1.13 on 2026-03-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jerseyNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
