# Generated by Django 4.1.13 on 2026-03-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_player_jerseynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
